### ISSUE TITLE
Inventory used space total not updating

### ISSUE THREAD

**Issue by voidbeast** [prasoc/BetterUI#25]
This issue seems similar to #21, sub-item 5, however that post only mentions the totals in the banking module, whereas this issue is in the inventory module, and after some experimentation, it appears to operate independently from the aforementioned banking module display issue. 

The number of used slots in the inventory does not update when items are removed from the inventory for any reason. The only way I can get it to refresh is to reloadui. Closing and reopening the inventory, switching to crafting bag and back, and switching categories all fail to update the total. In fact, in the bank interface, I can get the total displayed in the banking module to update by switching from the bank panel to the inventory panel; however, if I open the inventory interface after leaving the bank, it will still be showing the previous, incorrect number--whatever the total was before depositing items in the bank. No exceptions are being thrown, and it doesn't seem to affect the functionality; the number quantifying the used space in inventory just doesn't actively update as it changes. 

It seems to occur in all cases where the total number of slots used changes, whether the inventory module is open or not, and regardless of where the item is coming from or going to. I've checked each of these cases, and the issue was present after each: selling to/buying from merchants, using items directly from the inventory, opening containers from the inventory, equipping/removing items, receiving quest rewards, looting items from corpses/containers, enchanting items, destroying items, researching an item being carried in inventory, items that get used indirectly by a game action (lockpicks, specifically). In each of these cases, the inventory module ends up out of sync with the true value and remains so until it gets reloaded.  

I don't know if there are any log files that would help, or some sort of debug function I could activate to make it generate logs... If so, let me know, I'd be happy to help. Even with this issue, I still think this addon makes the UI a lot more convenient to use and I much prefer it to the base game UI, so I'll gladly do anything if it will help make it even better. Thanks for all your hard work =)

**Comment by esotericist** [comment]
I also was experiencing this problem.

I did some digging, and it looks like the problem is that BUI.GenericFooter.Refresh() is only called during initialization, doesn't seem to get called during any of the normal refresh stuff.

So around here:
https://github.com/prasoc/BetterUI/blob/master/Modules/Inventory/Inventory.lua#L356

I added
`    BUI.GenericFooter.Refresh(self)`

This appears to address the issue with both gold and item count updates.

Not in a position to set up a fork to do a pull request, and besides, I'm not familiar with the ESO addon ecosystem or this codebase, so I have no idea if that's the _right_ place for the footer refresh, all I know is it is _a_ place that seems to get the results I want.

**Comment by j-blandford** [comment]
Thank you for the debugging, it really helps! I will push a commit ASAP (after my exams) which will add it in
prasoc

**Comment by esotericist** [comment]
Glad to have assisted! I think the bank problems are beyond me, though, so I can't help with that one.

It, at least, is technically usable if clunkier than intended; the base inventory UI not updating capacity was more crippling.

**Comment by j-blandford** [comment]
There is a major update in the works, all thanks to @trentapple - he really went through and fixed a lot of remaining issues
I hope that with you both it will be as stable as it used to be :)

**Comment by esotericist** [comment]
I was actually already using what's currently in the repo; downloaded as a zip a few hours ago, extracted all relevant files.

**Comment by j-blandford** [comment]
thats good to hear - how has it been running? I haven't updated the ESOUI package yet, so no one has really tested the new version

**Comment by esotericist** [comment]
Well, I didn't really use it significantly prior to the @trentapple  updates, primarily because I couldn't cope with the inventory not updating, and I switched to the current commit in my troubleshooting before eventually making the above edit.

So basically, I'm only really familiar with this version, so it's hard for me to see what may or may not be working as expected versus the current published release. If I run into any problems, I'll submit a new issue.

**Comment by j-blandford** [comment]
ok, thank you and I hope you enjoy how BUI alters the gamepad interface :)

**Comment by trentapple** [comment]
This will bother me now that @voidbeast pointed it out, ha. 😆 Seems like it can be fixed with a minimal to no impact on performance.
